### ISSUE TITLE
The site is down that links to the doxygen output

### ISSUE THREAD

**Issue by jessicaengel451** [nullromo/doxygen-example#1]
Thanks for the tutorial :) Not sure if you were aware of this

**Comment by nullromo** [comment]
Thank you for pointing this out. I originally made this repository for internal use at my company, and I later cleaned it up and moved it to GitHub. The company was using GitLab, so that link pointed to the internal version built by GitLab CI (see the `.gitlab-ci.yml` file in the repo.

I just added a GitHub CI setup and the site is now hosted through GitHub Pages, so if you check the link again on the `main` branch, you should see it working correctly.
